# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
deployment:
  kind: DaemonSet

logs:
  access:
    enabled: true

globalArguments:
  - "--global.checknewversion"
  - "--global.sendanonymoususage"

### For now we only use http ###
# When https will be needed, uncomment the redirections lines
#
additionalArguments:
  - "--entryPoints.web.http.redirections.entryPoint.to=:443"
  - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
  - "--entryPoints.web.http.redirections.entryPoint.permanent=true"
# - "--metrics=true"
# - "--tracing=true"

ports:
  traefik:
    port: 9000
    expose: false
    exposedPort: 9000
    protocol: TCP
  web:
    port: 8000
    expose: true
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 8443
    expose: true
    exposedPort: 443
    protocol: TCP

service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: ${loadbalancer_ip}
